export const CATEGORIES_MAP = new Map([
  [1, ['content']],
  [2, ['customer-success']],
  [3, [['cybersecurity-it', ['security', 'it', 'technical-support']]]],
  [4, [['data-analytics', ['analytics', 'analysis-reporting', 'business-intelligence', 'data-engineering', 'data-science', 'machine-learning', 'management', 'other']]]],
  [5, ['design-ux']],
  [6, [['dev-engineering', ['android', 'cpp', 'c-sharp', 'devops', 'front-end', 'golang', 'java', 'javascript', 'hardware', 'ios', 'linux', 'management', 'net', 'perl', 'php', 'python', 'qa', 'ruby', 'salesforce', 'sales-engineer', 'scala', 'other']]]],
  [7, ['finance']],
  [8, ['hr']],
  [9, ['internships']],
  [10, ['legal']],
  [11, ['marketing']],
  [12, [['operations', ['office-management', 'operations-management', 'other']]]],
  [13, ['product']],
  [14, ['project-management']],
  [15, [['sales', ['account-executive', 'account-management', 'leadership', 'sales-operations', 'sales-development', 'sales-engineer']]]],
])

export const EXPERIENCE = ['entry-level', 'mid-level', 'senior']

export const INDUSTRY = [
  '3d-printing',
  '3pl-third-party-logistics',
  'adtech',
  'aerospace',
  'agency',
  'agriculture',
  'analytics-industry',
  'angel-vcfirm',
  'app-development',
  'appliances',
  'artificial-intelligence',
  'automation',
  'automotive',
  'beauty',
  'big-data',
  'big-data-analytics',
  'biotech',
  'blockchain',
  'business-intelligence-industry',
  'cannabis',
  'chemical',
  'cloud',
  'co-working-space-incubator',
  'computer-vision',
  'consulting',
  'consumer-web',
  'conversational-ai',
  'coupons',
  'cryptocurrency',
  'cybersecurity',
  'data-privacy',
  'database',
  'defense',
  'design',
  'digital-media',
  'ecommerce',
  'edtech',
  'energy',
  'enterprise-web',
  'esports',
  'events',
  'fashion',
  'financial-services',
  'fintech',
  'fitness',
  'food',
  'gaming',
  'generative-ai',
  'greentech',
  'hardware-industry',
  'healthtech',
  'hospitality',
  'hr-tech',
  'industrial',
  'information-technology',
  'infrastructure-as-a-service-iaas',
  'insurance',
  'iot',
  'kids-family',
  'legal-tech',
  'logistics',
  'machine-learning-industry',
  'manufacturing',
  'marketing-tech',
  'metaverse',
  'mobile',
  'music',
  'nanotechnology',
  'natural-language-processing',
  'news-entertainment',
  'nft',
  'on-demand',
  'other-industry',
  'payments',
  'pet',
  'pharmaceutical',
  'productivity',
  'professional-services',
  'proptech',
  'quantum-computing',
  'real-estate',
  'renewable-energy',
  'retail',
  'robotics',
  'sales-industry',
  'security-industry',
  'semiconductor',
  'seo',
  'sharing-economy',
  'social-impact',
  'social-media',
  'software',
  'solar',
  'sports',
  'telehealth',
  'transportation',
  'travel',
  'utilities',
  'virtual-reality',
  'wearables',
  'web3',
]

export const COMPANY_SIZE = [
  '1-10',
  '11-50',
  '51-200',
  '201-500',
  '501-1000',
  '1000',
]

export const WORK_OPTION = [
  'emote',
  'hybrid',
  'office',
]

export const LOCATION_MAP = new Map([[1, [['new-york-city', ['bronx', 'brooklyn', 'greater-new-york-area', 'manhattan', 'north-jersey', 'other-nyc-location', 'princeton-trenton']]]]])
